version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    ports:
      - "${postgres_port}:${postgres_internal_port}"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - socialnet_network

  db-migrations:
    image: liquibase/liquibase
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://${postgres_host}:${postgres_internal_port}/${postgres_db}
      LIQUIBASE_COMMAND_USERNAME: ${postgres_user}
      LIQUIBASE_COMMAND_PASSWORD: ${postgres_password}
    volumes:
      - ./changelog:/liquibase/changelog
    command: update --changelog-file=changelog-master.xml
    depends_on:
      - postgres
    networks:
      - socialnet_network

  frontend:
    container_name: frontend
    image: javapro38/social-net-dock:${front_tag}
    restart: unless-stopped
    ports:
      - "${frontend_port}:${frontend_internal_port}"
    networks:
      - socialnet_network

  user-service:
    container_name: user-service
    image: javapro38/soc-net-user-svc
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
      POSTGRES_HOST: ${postgres_host}
      POSTGRES_INTERNAL_PORT: ${postgres_internal_port}
      application_base_url: ${application_base_url}
      app_mail_username: ${app_mail_username}
      app_mail_password: ${app_mail_password}
      geoService_urlData: ${geoService_urlData}
      geonames_userName: ${geonames_userName}

    networks:
      - socialnet_network

  communications-service:
    container_name: communications-service
    image: javapro38/soc-net-comm-svc
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
      POSTGRES_HOST: ${postgres_host}
      POSTGRES_INTERNAL_PORT: ${postgres_internal_port}
      max_upload_file_size: ${max_upload_file_size}
      yandex_endpoint: ${yandex_endpoint}
      yandex_accesskey: ${yandex_accesskey}
      yandex_secretkey: ${yandex_secretkey}
      yandex_bucketname: ${yandex_bucketname}

    networks:
      - socialnet_network

  gateway-service:
    container_name: gateway-service
    image: javapro38/soc-net-gate-svc
    restart: unless-stopped
    depends_on:
      - user-service
      - communications-service
    environment:
      user_service_url: ${user_service_url}
      communications_service_url: ${communications_service_url}
      cors_origin: ${cors_origin}
      max_upload_file_size: ${max_upload_file_size}
    networks:
      - socialnet_network

volumes:
  data:
    driver: local

networks:
  socialnet_network:
    driver: bridge
