/*
 * This file is generated by jOOQ.
 */
package ru.team38.common.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.team38.common.jooq.tables.Notification;


/**
 * A class modelling indexes of tables in socialnet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_NOTIFICATION_AUTHOR_ID = Internal.createIndex(DSL.name("ix_notification_author_id"), Notification.NOTIFICATION, new OrderField[] { Notification.NOTIFICATION.AUTHOR_ID }, false);
    public static final Index IX_NOTIFICATION_RECEIVER_ID = Internal.createIndex(DSL.name("ix_notification_receiver_id"), Notification.NOTIFICATION, new OrderField[] { Notification.NOTIFICATION.RECEIVER_ID }, false);
}
