/*
 * This file is generated by jOOQ.
 */
package ru.team38.common.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in socialnet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>socialnet.file-storage_id_seq</code>
     */
    public static final Sequence<Long> FILE_STORAGE_ID_SEQ = Internal.createSequence("file-storage_id_seq", Socialnet.SOCIALNET, SQLDataType.BIGINT.nullable(false), 1, 1, 1, 9223372036854775807L, false, null);

    /**
     * The sequence <code>socialnet.friends_id_seq</code>
     */
    public static final Sequence<Long> FRIENDS_ID_SEQ = Internal.createSequence("friends_id_seq", Socialnet.SOCIALNET, SQLDataType.BIGINT.nullable(false), 1, 1, 1, 9223372036854775807L, false, null);

    /**
     * The sequence <code>socialnet.notification_id_seq</code>
     */
    public static final Sequence<Long> NOTIFICATION_ID_SEQ = Internal.createSequence("notification_id_seq", Socialnet.SOCIALNET, SQLDataType.BIGINT.nullable(false), 1, 1, 1, 9223372036854775807L, false, null);

    /**
     * The sequence <code>socialnet.tag_id_seq</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = Internal.createSequence("tag_id_seq", Socialnet.SOCIALNET, SQLDataType.BIGINT.nullable(false), 1, 1, 1, 9223372036854775807L, false, null);

    /**
     * The sequence <code>socialnet.tokens_id_seq</code>
     */
    public static final Sequence<Long> TOKENS_ID_SEQ = Internal.createSequence("tokens_id_seq", Socialnet.SOCIALNET, SQLDataType.BIGINT.nullable(false), 1, 1, 1, 9223372036854775807L, false, null);
}
