/*
 * This file is generated by jOOQ.
 */
package ru.team38.common.jooq.tables;


import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.team38.common.jooq.Keys;
import ru.team38.common.jooq.Socialnet;
import ru.team38.common.jooq.tables.records.CitiesRecord;


/**
 * Таблица для хранения городов
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cities extends TableImpl<CitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>socialnet.cities</code>
     */
    public static final Cities CITIES = new Cities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CitiesRecord> getRecordType() {
        return CitiesRecord.class;
    }

    /**
     * The column <code>socialnet.cities.id</code>. Уникальный идентификатор
     * города
     */
    public final TableField<CitiesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "Уникальный идентификатор города");

    /**
     * The column <code>socialnet.cities.city_name</code>. Название города
     */
    public final TableField<CitiesRecord, String> CITY_NAME = createField(DSL.name("city_name"), SQLDataType.VARCHAR(255), this, "Название города");

    /**
     * The column <code>socialnet.cities.country_id</code>. ID страны
     */
    public final TableField<CitiesRecord, Long> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.BIGINT, this, "ID страны");

    /**
     * The column <code>socialnet.cities.is_deleted</code>. Флаг, указывающий,
     * удален ли город
     */
    public final TableField<CitiesRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "Флаг, указывающий, удален ли город");

    /**
     * The column <code>socialnet.cities.latitude</code>. Широта
     */
    public final TableField<CitiesRecord, Double> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DOUBLE, this, "Широта");

    /**
     * The column <code>socialnet.cities.longitude</code>. Долгота
     */
    public final TableField<CitiesRecord, Double> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DOUBLE, this, "Долгота");

    /**
     * The column <code>socialnet.cities.zone_id</code>. Временная зона города
     */
    public final TableField<CitiesRecord, String> ZONE_ID = createField(DSL.name("zone_id"), SQLDataType.CLOB, this, "Временная зона города");

    private Cities(Name alias, Table<CitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cities(Name alias, Table<CitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Таблица для хранения городов"), TableOptions.table());
    }

    /**
     * Create an aliased <code>socialnet.cities</code> table reference
     */
    public Cities(String alias) {
        this(DSL.name(alias), CITIES);
    }

    /**
     * Create an aliased <code>socialnet.cities</code> table reference
     */
    public Cities(Name alias) {
        this(alias, CITIES);
    }

    /**
     * Create a <code>socialnet.cities</code> table reference
     */
    public Cities() {
        this(DSL.name("cities"), null);
    }

    public <O extends Record> Cities(Table<O> child, ForeignKey<O, CitiesRecord> key) {
        super(child, key, CITIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Socialnet.SOCIALNET;
    }

    @Override
    public UniqueKey<CitiesRecord> getPrimaryKey() {
        return Keys.CITIES_PKEY;
    }

    @Override
    public Cities as(String alias) {
        return new Cities(DSL.name(alias), this);
    }

    @Override
    public Cities as(Name alias) {
        return new Cities(alias, this);
    }

    @Override
    public Cities as(Table<?> alias) {
        return new Cities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(String name) {
        return new Cities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Name name) {
        return new Cities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Table<?> name) {
        return new Cities(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, Long, Boolean, Double, Double, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super Long, ? super Boolean, ? super Double, ? super Double, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super Long, ? super Boolean, ? super Double, ? super Double, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
